### ISSUE TITLE
Hera (elementaryOS 5.1) release on Docker Hub

### ISSUE THREAD

**Issue by willemavjc** [elementary/docker#11]
I just saw that elementaryOS is released as Docker images as well as plain OS (.iso downloadable on elementary.io). And this is great news as I'm discovering this distribution and would be happy to give it a try in a virtualized environment.

Still, on the [Docker Hub](https://hub.docker.com/r/elementary/docker), I am not sure whether or not there is the latest stable release called Hera.

If not, could it be possible to publish one or at least publish the procedure to make one myself? I am not familiar with making base images (from scratch) but I am ready to try.

Thanks!

**Comment by gamerlv** [comment]
As Hera is mostly a iso refresh the latest Juno image is actually the Hera release.

You can use the `elementary/docker:latest` image to get the newest version.

**Comment by willemavjc** [comment]
Oh okay. Thanks! I suppose we can close the issue then.

Would it not be simpler to make a proper label for it though?

**Comment by willemavjc** [comment]
I am not familiar with this distribution and there is no documentation on the way to properly launch it. I can connect to the container with a `docker container run -it elementary/docker:latest` but do you have any idea how to launch the graphical interface? (i.e. Pantheon if I got things right)

The elementaryOS' Docker Hub space lack a bit of explanations such the differences between standard images and -installer ones. =/
