### ISSUE TITLE
Include flatpak builder

### ISSUE THREAD

**Issue by danirabbit** [elementary/docker#16]
## Problem

Currently we have to install flatpak builder in every CI which we want to add flatpak to

## Proposal

pre-install flatpak builder

## Prior Art

docker.io/bilelmoussaoui/flatpak-github-actions

**Comment by cassidyjames** [comment]
Since we include the SDK in the docker image, this should be handled by https://github.com/elementary/seeds/issues/52, right?

https://github.com/elementary/docker/blob/ca1fa5b90a74b728d3d65cbef61fd8b9ec5426a1/odin-unstable/Dockerfile#L13

**Comment by danirabbit** [comment]
Actually yes, you're right. This is a duplicate. Closing
