### ISSUE TITLE
GitHub Publish Action Disabled

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/docker#23]
### What Happened?

The "Publish" action has disabled itself due to inactivity, so we don't have up to date docker images.

I don't have enough rights to re-enable, and this is causing the Wingpanel GTK4 CI to fail due to mismatched Mutter versions in the Docker image.

### Steps to Reproduce

Look at actions.

### Expected Behavior

Docker images build regularly 

### OS Version

Other Linux

### Software Version

Compiled from git

**Comment by davidmhewitt** [comment]
@danrabbit Apparently I don't even have rights to assign this to you or put it in a project, but this is a super easy one for you to close :wink: 

So, I thought I'd give you a ping instead!

**Comment by danirabbit** [comment]
Sorry about that! Rights on the project should be fixed and I re-enabled the workflow!
